name: dotnet package

on:
  push:
    branches: [main, develop]

jobs:
  build:

    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1'
      - name: Install dependencies
        run: dotnet restore GithubActionsTestProjectDotNet/GithubActionsTestProjectDotNet/Calculator.csproj
      - name: Build
        run: dotnet build GithubActionsTestProjectDotNet/GithubActionsTestProjectDotNet/Calculator.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test GithubActionsTestProjectDotNet/CalculatorTests/CalculatorTests.csproj --no-restore --verbosity normal
      - name: XUnit Viewer
      - id: xunit-viewer
        uses: AutoModality/action-xunit-viewer@v1  #use the current project relative to root
      - name: The generated report
        run: echo "The report is ${{ steps.xunit-viewer.outputs.report-file }}"    
      - name: Test
        run: |
            [ ${{ steps.xunit-viewer.outputs.report-file }} == "test-reports/index.html" ]
      - name: Attach the report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: ${{ steps.xunit-viewer.outputs.report-dir }}
